name = "GBK"
uuid = "f60d2a9e-e6c3-11e9-1104-51987764600f"
authors = ["Yao Lu <luyaocns@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
